---
- name: Install basic packages
  apt:
      pkg:
        #tshoot
        - strace
        - bpftrace
        - atop
        - iotop
        - dnsutils 
        - procps 
        - inotify-tools
        - iftop
        - net-tools
        - lsof
        - rsyslog

        #handy tool
        - vmtouch
        - curl
        - wget

        #sec
        - nmap

        #editor
        - vim
        - screen
      state: latest
      update_cache: yes