---
- name: Update settings defined in vars file
  sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}' 
    state: present
    reload: yes
  with_dict: '{{ general_settings_sysctl_config }}'
